apiVersion: v1
kind: Service
metadata:
  name: ftps-alpine
  labels:
    app: ftps-alpine
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  type: LoadBalancer
  ports:
  - name: ftp21
    port: 21
    targetPort: 21
    protocol: TCP
  - name: ftp30020
    port: 30020
    targetPort: 30020
    protocol: TCP
  - name: ftp30021
    port: 30021
    targetPort: 30021
    protocol: TCP
  selector:
    run: ftps-alpine
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-alpine
spec:
  replicas: 1
  selector:
    matchLabels:
      run: ftps-alpine
  template:
    metadata:
      labels:
        run: ftps-alpine
    spec:
      containers:
      - name: ftps-alpine
        image: ftps_img
        imagePullPolicy: Never
        ports:
        - containerPort: 21
        - containerPort: 30020
        - containerPort: 30021
        volumeMounts:
          - name: ftps-persistent-storage
            mountPath: /home
      volumes:
      - name: ftps-persistent-storage
        persistentVolumeClaim:
          claimName: ftps-pvc
